### ISSUE TITLE
Add "How to Contribute" Section to README.md

### ISSUE THREAD

**Issue by Snehshishdutta** [Namit2111/Linkedin-to-resume#10]
Hi @Namit2111 ,

I’d like to propose adding a "How to Contribute" section to the README file. This would help newcomers understand how they can get involved with the project. Here are some suggested points to include:

1.Forking the Repository
2.Cloning the Repository
3.Creating a New Branch
4.Making Changes
5.Committing Changes
6.Pushing Changes
7.Opening a Pull Request
8.Waiting for Review

This addition would enhance the accessibility of the project and encourage more contributions.
Could you please assign me this issue under the label "hacktoberfest" and "hacktoberfestaccepted"?

**Comment by codebydeep** [comment]
Heyy @Snehshishdutta I want to contribute to this issue. Can you assign it to me ?
